name: Build and Deploy .NET Core 8 Project to Windows VM

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 1: Setup .NET SDK
    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # Use the .NET 8 SDK

    # Step 2: Restore dependencies
    - name: Restore dependencies
      run: |
        dotnet restore

    # Step 3: Build the project
    - name: Build project
      run: |
        dotnet build --configuration Release

    # Step 4: Publish the application (output folder for deployment)
    - name: Publish application
      run: |
        dotnet publish --configuration Release --output ./publish
