name: Deploy .NET Core 8 App to Azure Windows VM

on:
  push:
    branches:
      - main  # Trigger the deployment when code is pushed to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # The runner to execute the job

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the latest code from the repo

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'  # Specify the .NET Core version

    - name: Restore dependencies
      run: dotnet restore  # Restore any dependencies defined in the .csproj file

    - name: Build the application
      run: dotnet build --configuration Release  # Build the application in release mode

    - name: Publish the application
      run: dotnet publish --configuration Release --output ./publish  # Publish the app

    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.5.3  # Setup SSH agent for SSH connection
      with:
        ssh-private-key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}

    - name: Deploy to Azure VM
      run: |
        # Deploy the app to the Azure VM using SSH
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_IP }} << 'EOF'
          # Stop the existing .NET app if it's running
          Stop-Process -Name "dotnet" -Force
          
          # Navigate to the folder where the app will be deployed
          cd C:\Users\tdsadmin\test
          
          # Remove any existing files from the previous deployment
          Remove-Item -Recurse -Force .\*
          
          # Copy the new published files
          Copy-Item -Recurse -Force C:\Users\tdsadmin\test\* C:\Users\tdsadmin\test\
          
          # Start the .NET application
          Start-Process "dotnet" "YourApp.dll"
        EOF
