name: CI/CD for .NET Core 8 App with IIS Deployment

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Run on a Linux-based runner

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the application
        run: dotnet build --configuration Release

      - name: Publish the application
        run: dotnet publish --configuration Release --output ${{ github.workspace }}/artifactdirectory


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}

      - name: Copy files to Azure VM
        run: |
          scp -r ./publish/* tdsadmin@20.127.226.1:C:\inetpub\wwwroot\code

      - name: Restart IIS on Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no tdsadmin@20.127.226.1 << 'EOF'
            # Restart IIS to apply changes
            iisreset
          EOF
