name: Deploy .NET Core 8 App to Azure Windows VM via SSH

on:
  push:
    branches:
      - main  # Adjust as needed

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core 8 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

    - name: Publish project
      run: |
        dotnet publish -c Release -o published

    - name: Install SSH client
      run: |
        Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0

    - name: Copy files to Azure VM using SCP (PowerShell)
      shell: pwsh
      run: |
       $user = "${{ secrets.AZURE_VM_USERNAME }}"
       $ip = "${{ secrets.AZURE_VM_IP }}"
       $port = "${{ secrets.AZURE_VM_PORT }}"
       $remotePath = "/c/inetpub/wwwroot/myapp/"
       $scpTarget = "${user}@${ip}:$remotePath"
       scp -o StrictHostKeyChecking=no -P $port -r .\published\* $scpTarget
      env:
        SSHPASS: ${{ secrets.AZURE_VM_PASSWORD }}

    - name: Remote restart IIS (or custom app command)
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.AZURE_VM_PORT }} ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_IP }} 
            "powershell Restart-Service -Name 'W3SVC'"
      env:
        SSHPASS: ${{ secrets.AZURE_VM_PASSWORD }}
