name: Deploy .NET Core MVC App to Ubuntu Server

on:
   push:
       branches:
         - main

jobs:
     build:
       runs-on: ubuntu-latest

       steps:
       - name: Checkout code
         uses: actions/checkout@v2

       - name: Set up .NET Core SDK
         uses: actions/setup-dotnet@v2
         with:
           dotnet-version: '8.0.x'

       - name: Restore dependencies
         run: dotnet restore

       - name: Build the application
         run: dotnet build --configuration Release

       - name: Publish the application
         run: dotnet publish --configuration Release --output ./publish

       - name: Upload published files as artifact
         uses: actions/upload-artifact@v2
         with:
           name: published-app
           path: ./publish

     deploy:
       runs-on: ubuntu-latest
       needs: build
       steps:
       - name: Download published files
         uses: actions/download-artifact@v2
         with:
           name: published-app
           path: ./published-app

       - name: Deploy to Ubuntu Server via SSH
         uses: appleboy/ssh-action@v0.1.8
         with:
           host: ${{ secrets.AZURE_VM_IP }}
           username: ${{ secrets.AZURE_VM_USERNAME }}
           key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
           port: 22
           script: |
             
             # Copy new published files to the app directory
             cp -r ./published-app/* /home/tdsadmin/test/
