name: .NET Core 8 CI/CD to Azure Windows VM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # You can use any GitHub runner to build your app

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Specify the version of .NET Core 8

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --configuration Release

      - name: Publish the app
        run: dotnet publish --configuration Release --output ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure the build job is completed before deploying

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass (for password-based authentication)
        run: sudo apt-get install -y sshpass

      - name: Deploy to Azure Windows VM
        run: |
          # Use sshpass to pass the password non-interactively for SSH authentication
          sshpass -p ${{ secrets.AZURE_VM_PASSWORD }} ssh -o StrictHostKeyChecking=no -p 22 tdsadmin@20.127.226.1 "powershell.exe -Command 'C:\\Users\\tdsadmin\\deploy.ps1'"
        env:
          AZURE_VM_PASSWORD: ${{ secrets.AZURE_VM_PASSWORD }}
